MVC_Project/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Project.DataAccess;
using MVC_Project.Models;

namespace MVC_Project.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Companies.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Symbol == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Symbol,Name,Date,IsEnabled,Type,IexId")] Company company)
        {
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Symbol,Name,Date,IsEnabled,Type,IexId")] Company company)
        {
            if (id != company.Symbol)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Symbol))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Symbol == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var company = await _context.Companies.FindAsync(id);
            _context.Companies.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(string id)
        {
            return _context.Companies.Any(e => e.Symbol == id);
        }
    }
}

MVC_Project/Controllers/CompanyStats1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Project.DataAccess;
using MVC_Project.Models;

namespace MVC_Project.Controllers
{
    public class CompanyStats1Controller : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompanyStats1Controller(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CompanyStats1
        public async Task<IActionResult> Index()
        {
            return View(await _context.CompanyStats.ToListAsync());
        }

        // GET: CompanyStats1/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyStats = await _context.CompanyStats
                .FirstOrDefaultAsync(m => m.Symbol == id);
            if (companyStats == null)
            {
                return NotFound();
            }

            return View(companyStats);
        }

        // GET: CompanyStats1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CompanyStats1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Symbol,CompanyName,MarketCap,Revenue,GrossProfit,Debt")] CompanyStats companyStats)
        {
            if (ModelState.IsValid)
            {
                _context.Add(companyStats);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(companyStats);
        }

        // GET: CompanyStats1/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyStats = await _context.CompanyStats.FindAsync(id);
            if (companyStats == null)
            {
                return NotFound();
            }
            return View(companyStats);
        }

        // POST: CompanyStats1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Symbol,CompanyName,MarketCap,Revenue,GrossProfit,Debt")] CompanyStats companyStats)
        {
            if (id != companyStats.Symbol)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyStats);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyStatsExists(companyStats.Symbol))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(companyStats);
        }

        // GET: CompanyStats1/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyStats = await _context.CompanyStats
                .FirstOrDefaultAsync(m => m.Symbol == id);
            if (companyStats == null)
            {
                return NotFound();
            }

            return View(companyStats);
        }

        // POST: CompanyStats1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var companyStats = await _context.CompanyStats.FindAsync(id);
            _context.CompanyStats.Remove(companyStats);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyStatsExists(string id)
        {
            return _context.CompanyStats.Any(e => e.Symbol == id);
        }
    }
}

MVC_Project/Controllers/CompanyStatsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Project.DataAccess;
using MVC_Project.Models;
using Newtonsoft.Json;

namespace MVC_Project.Controllers
{
    
    public class CompanyStatsController : Controller
    {
        public ApplicationDbContext dbContext;
        //Base URL for the IEXTrading API. Method specific URLs are appended to this base URL.
        string BASE_URL = "https://api.iextrading.com/1.0/";
        HttpClient httpClient;

        /*
             These lines create a Constructor for the HomeController.
             Then, the Database context is defined in a variable.
             Then, an instance of the HttpClient is created.

        */
        public CompanyStatsController(ApplicationDbContext context)
        {
            dbContext = context;

            httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Accept.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new
                System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        /*
            Calls the IEX reference API to get the list of symbols.
            Returns a list of the companies whose information is available. 
        */
        public CompanyStats GetCompanyStats(string symbol)
        {

        CompanyStats companyStats = new CompanyStats();
        string IEXTrading_API_PATH = BASE_URL + "/stock/" + symbol + "/stats";

        string statList = "";
        //List<Divident> dividends1 = new List<Divident>();
          httpClient.BaseAddress = new Uri(IEXTrading_API_PATH);
        
        HttpResponseMessage respose = httpClient.GetAsync(IEXTrading_API_PATH).GetAwaiter().GetResult();

          if (respose.IsSuccessStatusCode)
            {
                  statList = respose.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            }
                  if (!statList.Equals(""))
                    {

                    companyStats = JsonConvert.DeserializeObject<CompanyStats>(statList);
                      //companyStats.GetRange(0, companyStats.Le);
                    }
         //dividends.AddRange(dividends1);
          return companyStats;

        }
        //[Route("{Name}/{id}")]
        public IActionResult CompanyStat(string Name,string id)
        {
                  string symbol = id;
                ViewBag.dbSuccessComp = 0;
              CompanyStats companystat = GetCompanyStats(symbol);
            TempData["companystat"] = JsonConvert.SerializeObject(companystat);
          return View(companystat);

        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_Project/Controllers/DividentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Project.DataAccess;
using MVC_Project.Models;

namespace MVC_Project.Controllers
{
    public class DividentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DividentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dividents
        public async Task<IActionResult> Index()
        {
            return View(await _context.Divident.ToListAsync());
        }

        // GET: Dividents/Details/5
        public async Task<IActionResult> Details(DateTime? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var divident = await _context.Divident
                .FirstOrDefaultAsync(m => m.Exdate == id);
            if (divident == null)
            {
                return NotFound();
            }

            return View(divident);
        }

        // GET: Dividents/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dividents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Exdate,Payment_date,Record_date,Amount,type")] Divident divident)
        {
            if (ModelState.IsValid)
            {
                _context.Add(divident);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(divident);
        }

        // GET: Dividents/Edit/5
        public async Task<IActionResult> Edit(DateTime? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var divident = await _context.Divident.FindAsync(id);
            if (divident == null)
            {
                return NotFound();
            }
            return View(divident);
        }

        // POST: Dividents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DateTime id, [Bind("Exdate,Payment_date,Record_date,Amount,type")] Divident divident)
        {
            if (id != divident.Exdate)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(divident);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DividentExists(divident.Exdate))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(divident);
        }

        // GET: Dividents/Delete/5
        public async Task<IActionResult> Delete(DateTime? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var divident = await _context.Divident
                .FirstOrDefaultAsync(m => m.Exdate == id);
            if (divident == null)
            {
                return NotFound();
            }

            return View(divident);
        }

        // POST: Dividents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(DateTime id)
        {
            var divident = await _context.Divident.FindAsync(id);
            _context.Divident.Remove(divident);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DividentExists(DateTime id)
        {
            return _context.Divident.Any(e => e.Exdate == id);
        }
    }
}

MVC_Project/Views/Shared/Index.cshtml
@model IEnumerable<MVC_Project.Models.Company>

@{
    ViewData["Title"] = "Company";
}
<h2>Index</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsEnabled)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IexId)
            </th>
            <th>Dividends</th>
            <th>Company Statistics</th>
            <th>Logos</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsEnabled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IexId)
            </td>
            <td>
                <a asp-controller="Home" asp-route-id="@item.Symbol" asp-action="Divident">Dividends</a>
            </td>
            <td>
                <a asp-controller="CompanyStats"  asp-route-name ="@item.Name" asp-route-id="@item.Symbol" asp-action="CompanyStat">Stats</a>
            </td>
            <td>
                <a asp-controller="Home" asp-route-id="@item.Symbol" asp-action="Logo">Logo</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVC_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Project</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MVC_Project</a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Sectors" asp-action="Sector">Sector</a></li>
                    <li><a asp-controller="Home" asp-action="AboutUs">AboutUs</a></li>
                    <li><a asp-controller="Companies" asp-action="Index">Insert Companies</a></li>
                    <li><a asp-controller="CompanyStats1" asp-action="Index">Insert Company_Stat</a></li>
                    <li><a asp-controller="Dividents" asp-action="Index">Insert Dividents</a></li>
                    
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - MVC_Project</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>